### PR TITLE
Refactor to use Shaka Preload API

### PR DESCRIPTION
**Pull request by enjikaka**
Shaka has release the Preload API now which lets us get rid of our hack of using 2 instances of shaka-player to be able to preload upcoming songs.

- Remove the seconds HTMLMediaElement
- shaka PreloadManager does not provide the duration until load, so added logic to parse that from the manifest instead
- added currentStreamingSessionId fallback to handle race conditions when doing preload+load quickly. (@osmestad that is what triggered `Missing data for DRM request filter.`, so those errors should be reduced)

### CODE REVIEW

**Comment by enjikaka** [comment]
The next tests are failing since Shaka cannot preload static files. I tried switching the streaming formats for the test API token to use dash. So hoping they should be green in a rerun when the change has propagated in the API!

**Review by osmestad — APPROVED** [review]

**Comment by enjikaka** [comment]
Tests are finally green. For reference I changed the related GitHub secrets for the test user. So something was up with authentication. Should probable add some pre-test check that auth is in good order before continuing!

**Comment by enjikaka** [comment]
I need to do some manual testing with native player <-> shaka player switching to verify I do not break anything there, before we can merge this.

**Comment by enjikaka** [comment]
We do have an issue in desktop with native player in the test playlist. However there is no difference in this PR to main so this is safe to merge!

**Pull request merged**
