### PR TITLE
[Player] Remove playback progress event

### PR DESCRIPTION
**Pull request by enjikaka**
The playback progress event has been used for the "Recently Playing" module on the home page. Our API now uses the playlog events instead to derive that information. So this is redundant. Removing!

Branched from #92, #91 and #92 needs to be merged first.

### CODE REVIEW

**Review by osmestad — APPROVED** [review]

**Comment by osmestad** [comment]
I assume it is not needed for Podcast progress anymore either then?

**Comment by enjikaka** [comment]
> I assume it is not needed for Podcast progress anymore either then?

Correct!

**Comment by enjikaka** [comment]
We're going to wait a little bit more before doing this!

**Comment by osmestad** [comment]
done in #158

**Pull request closed without merging**
